### PR TITLE
Use https version of the Vimeo API endpoint

### PR DESCRIPTION
**Pull request by jhass**
Looks like it mirrors the scheme used there now.

### CODE REVIEW

**Comment by jhass** [comment]
I see #45 merged, any feedback on this one?

**Comment by metavida** [comment]
Oh, shoot! Sorry that I missed this one in yesterday's release & thanks for the bump. I'll keep this browser tab open & try to get a new tiny release out with this pull in the next day or three.

**Comment by metavida** [comment]
Alrighty @jhass, the https Vimeo endpoint is now part of v0.8.14. Thanks for the contribution!!

**Comment by jhass** [comment]
Thanks!

**Pull request merged**
