### PR TITLE
Prefer HTTPS endpoints

### PR DESCRIPTION
**Pull request by javan**
Updated providers to use HTTPS endpoints where I was able to confirm their availability.

### CODE REVIEW

**Comment by metavida** [comment]
@javan sorry for the silence on this one. I would have merged this one long ago, but I'm having problems with my local setup (or at least I *think* they're local problems). I wanted to test each now-HTTPS provider locally to confirm things are working as expected, but I keep running into an odd SSL error every time I try the Youtube provider:

```ruby
RUBY_VERSION #=> "2.2.3"
require 'oembed' #=> true 
OEmbed::VERSION #=> "0.8.14"
OEmbed::Providers::Youtube.get("https://youtu.be/blSl487coFg")
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /Users/marcoswk/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/marcoswk/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/marcoswk/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /Users/marcoswk/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/marcoswk/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/marcoswk/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/marcoswk/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/marcoswk/workspace/ruby-oembed/lib/oembed/provider.rb:146:in `raw'
	from /Users/marcoswk/workspace/ruby-oembed/lib/oembed/provider.rb:86:in `get'
	from (irb):2
	from /Users/marcoswk/.rvm/rubies/ruby-2.2.3/bin/irb:15:in `<main>'
```

Over the past months, I've occasionally tried [to fix up my local install](http://railsapps.github.io/openssl-certificate-verify-failed.html) but just can't seem to get that error to go away, and then run out of time & have to move on to other projects.

Also, the fact that I'm running into this error on what I consider a pretty standard rvm setup makes me worry that other devs would also be blocked by this issue if I were to merge this pull request.

So sorry for all this delay! If you have any advice on how I can work around this, that'd be awesome. Regardless, I'll keep plugging away until I can get this pull request merged.

**Comment by metavida** [comment]
Phew! I had a bit more time to work this out & confirmed that my local OpenSSL config was a bit borked (and that your pull request was awesome :rocket: ).

In case anyone else wanders upon this post, I finally found my solution via [this detailed blog post](http://mislav.uniqpath.com/2013/07/ruby-openssl/) and [it's accompanying tool](https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb).

My final solution:
* `brew reinstall openssl` 
* symlink `/etc/openssl` to `/usr/local/etc/openssl`

**Comment by javan** [comment]
Thanks! ❤️

**Comment by metavida** [comment]
This change is at long, long last part of ruby-oembed 0.9.0 which I just pushed to rubygems.

**Pull request merged**
