### PR TITLE
Support redirects in ProviderDiscovery

### PR DESCRIPTION
**Pull request by svoop**
Provider discovery currently fails if Youtube returns a 301 redirect which happens more often lately. This simple patch fixes the problem.

I'm not familiar with VCR, you might want to add a test for this.

### CODE REVIEW

**Comment by svoop** [comment]
Any chance to get this merged?

**Comment by metavida** [comment]
So sorry for the slowness. I've been swamped at work & with family. I'm going to try to release a new version of the gem next week & if I'm lucky I'll have time to get this tested & included.

**Comment by svoop** [comment]
No problem, I was just skimming over my forks and stumbled over this issue which must affect other users as well. Thanks for taking a look!

**Comment by metavida** [comment]
ruby-oembed 0.9.0 is now on rubygems & its ProviderDiscovery now fully support for redirects! You can even pass a `:max_redirects` options if you don't like the default of 4 redirects:

```ruby
response = OEmbed::ProviderDiscovery.get(uri, :max_redirects=>2)
```

**Comment by svoop** [comment]
Cool, thanks a lot!

**Pull request closed without merging**
